<?php

/**
 * This is the model base class for the table "rental".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rental".
 *
 * Columns in table "rental" available as properties of the model,
 * followed by relations of table "rental" available as properties of the model.
 *
 * @property integer $rental_id
 * @property string $rental_date
 * @property integer $inventory_id
 * @property integer $customer_id
 * @property string $return_date
 * @property integer $staff_id
 * @property string $last_update
 *
 * @property Payment[] $payments
 * @property Staff $staff
 * @property Inventory $inventory
 * @property Customer $customer
 */
abstract class BaseRental extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rental';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rental|Rentals', $n);
	}

	public static function representingColumn() {
		return 'rental_date';
	}

	public function rules() {
		return array(
			array('rental_date, inventory_id, customer_id, staff_id, last_update', 'required'),
			array('inventory_id, customer_id, staff_id', 'numerical', 'integerOnly'=>true),
			array('return_date', 'safe'),
			array('return_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'payments' => array(self::HAS_MANY, 'Payment', 'rental_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'inventory' => array(self::BELONGS_TO, 'Inventory', 'inventory_id'),
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'rental_id' => Yii::t('app', 'Rental'),
			'rental_date' => Yii::t('app', 'Rental Date'),
			'inventory_id' => null,
			'customer_id' => null,
			'return_date' => Yii::t('app', 'Return Date'),
			'staff_id' => null,
			'last_update' => Yii::t('app', 'Last Update'),
			'payments' => null,
			'staff' => null,
			'inventory' => null,
			'customer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('rental_id', $this->rental_id);
		$criteria->compare('rental_date', $this->rental_date, true);
		$criteria->compare('inventory_id', $this->inventory_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('return_date', $this->return_date, true);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}