<?php

/**
 * This is the model base class for the table "city".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "City".
 *
 * Columns in table "city" available as properties of the model,
 * followed by relations of table "city" available as properties of the model.
 *
 * @property integer $city_id
 * @property string $city
 * @property integer $country_id
 * @property string $last_update
 *
 * @property Address[] $addresses
 * @property Country $country
 */
abstract class BaseCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'city';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'City|Cities', $n);
	}

	public static function representingColumn() {
		return 'city';
	}

	public function rules() {
		return array(
			array('city, country_id, last_update', 'required'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('city', 'length', 'max'=>50),
			array('city_id, city, country_id, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'addresses' => array(self::HAS_MANY, 'Address', 'city_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'city_id' => Yii::t('app', 'City'),
			'city' => Yii::t('app', 'City'),
			'country_id' => null,
			'last_update' => Yii::t('app', 'Last Update'),
			'addresses' => null,
			'country' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}