<?php

/**
 * This is the model base class for the table "actor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Actor".
 *
 * Columns in table "actor" available as properties of the model,
 * followed by relations of table "actor" available as properties of the model.
 *
 * @property integer $actor_id
 * @property string $first_name
 * @property string $last_name
 * @property string $last_update
 *
 * @property Film[] $films
 */
abstract class BaseActor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'actor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Actor|Actors', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('first_name, last_name, last_update', 'required'),
			array('first_name, last_name', 'length', 'max'=>45),
			array('actor_id, first_name, last_name, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'films' => array(self::MANY_MANY, 'Film', 'film_actor(actor_id, film_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'films' => 'FilmActor',
		);
	}

	public function attributeLabels() {
		return array(
			'actor_id' => Yii::t('app', 'Actor'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'last_update' => Yii::t('app', 'Last Update'),
			'films' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('actor_id', $this->actor_id);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}