<?php

/**
 * This is the model base class for the table "address".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Address".
 *
 * Columns in table "address" available as properties of the model,
 * followed by relations of table "address" available as properties of the model.
 *
 * @property integer $address_id
 * @property string $address
 * @property string $address2
 * @property string $district
 * @property integer $city_id
 * @property string $postal_code
 * @property string $phone
 * @property string $last_update
 *
 * @property City $city
 * @property Customer[] $customers
 * @property Staff[] $staffs
 * @property Store[] $stores
 */
abstract class BaseAddress extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'address';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Address|Addresses', $n);
	}

	public static function representingColumn() {
		return 'address';
	}

	public function rules() {
		return array(
			array('address, district, city_id, phone, last_update', 'required'),
			array('city_id', 'numerical', 'integerOnly'=>true),
			array('address, address2', 'length', 'max'=>50),
			array('district, phone', 'length', 'max'=>20),
			array('postal_code', 'length', 'max'=>10),
			array('address2, postal_code', 'default', 'setOnEmpty' => true, 'value' => null),
			array('address_id, address, address2, district, city_id, postal_code, phone, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'customers' => array(self::HAS_MANY, 'Customer', 'address_id'),
			'staffs' => array(self::HAS_MANY, 'Staff', 'address_id'),
			'stores' => array(self::HAS_MANY, 'Store', 'address_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'address_id' => Yii::t('app', 'Address'),
			'address' => Yii::t('app', 'Address'),
			'address2' => Yii::t('app', 'Address2'),
			'district' => Yii::t('app', 'District'),
			'city_id' => null,
			'postal_code' => Yii::t('app', 'Postal Code'),
			'phone' => Yii::t('app', 'Phone'),
			'last_update' => Yii::t('app', 'Last Update'),
			'city' => null,
			'customers' => null,
			'staffs' => null,
			'stores' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('address_id', $this->address_id);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('address2', $this->address2, true);
		$criteria->compare('district', $this->district, true);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('postal_code', $this->postal_code, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}