<?php

/**
 * This is the model base class for the table "customer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Customer".
 *
 * Columns in table "customer" available as properties of the model,
 * followed by relations of table "customer" available as properties of the model.
 *
 * @property integer $customer_id
 * @property integer $store_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $address_id
 * @property integer $active
 * @property string $create_date
 * @property string $last_update
 *
 * @property Address $address
 * @property Store $store
 * @property Payment[] $payments
 * @property Rental[] $rentals
 */
abstract class BaseCustomer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'customer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Customer|Customers', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('store_id, first_name, last_name, address_id, create_date, last_update', 'required'),
			array('store_id, address_id, active', 'numerical', 'integerOnly'=>true),
			array('first_name, last_name', 'length', 'max'=>45),
			array('email', 'length', 'max'=>50),
			array('email, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('customer_id, store_id, first_name, last_name, email, address_id, active, create_date, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'address' => array(self::BELONGS_TO, 'Address', 'address_id'),
			'store' => array(self::BELONGS_TO, 'Store', 'store_id'),
			'payments' => array(self::HAS_MANY, 'Payment', 'customer_id'),
			'rentals' => array(self::HAS_MANY, 'Rental', 'customer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'customer_id' => Yii::t('app', 'Customer'),
			'store_id' => null,
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'email' => Yii::t('app', 'Email'),
			'address_id' => null,
			'active' => Yii::t('app', 'Active'),
			'create_date' => Yii::t('app', 'Create Date'),
			'last_update' => Yii::t('app', 'Last Update'),
			'address' => null,
			'store' => null,
			'payments' => null,
			'rentals' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('store_id', $this->store_id);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('address_id', $this->address_id);
		$criteria->compare('active', $this->active);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}