<?php

/**
 * This is the model base class for the table "country".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Country".
 *
 * Columns in table "country" available as properties of the model,
 * followed by relations of table "country" available as properties of the model.
 *
 * @property integer $country_id
 * @property string $country
 * @property string $last_update
 *
 * @property City[] $cities
 */
abstract class BaseCountry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'country';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Country|Countries', $n);
	}

	public static function representingColumn() {
		return 'country';
	}

	public function rules() {
		return array(
			array('country, last_update', 'required'),
			array('country', 'length', 'max'=>50),
			array('country_id, country, last_update', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'City', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'country_id' => Yii::t('app', 'Country'),
			'country' => Yii::t('app', 'Country'),
			'last_update' => Yii::t('app', 'Last Update'),
			'cities' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('last_update', $this->last_update, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}