<?php

/**
 * This is the model base class for the table "film_text".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Film_text".
 *
 * Columns in table "film_text" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $film_id
 * @property string $title
 * @property string $description
 *
 */
abstract class BaseFilm_text extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'film_text';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Film_text|Film_texts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('film_id, title', 'required'),
			array('film_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('film_id, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'film_id' => Yii::t('app', 'Film'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('film_id', $this->film_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}